import { Inter } from "next/font/google";
import Link from 'next/link';
import "../../../public/bootstrap/css/bootstrap.min.css";
import '../../../public/css/admin.css';
import Leftbar from "./component/leftbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <head>
                <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet' />
            </head>
            <body className={inter.className}>
                <div className="container-1">
                    <div className="container-all-content">
                        <Leftbar />
                        <div className="container-right">
                            <div className="header-right-top-content-all">
                                <div className="header-right-top-content">
                                    <div className="header-right-top-content-icon">
                                        <i className="fa-solid fa-bars"></i>
                                    </div>
                                    <div className="header-right-top-content">
                                        <span>Và Oke nó gọi chẳng mấy khi!</span> <br />
                                        <span>Liên Hệ: NTN</span>
                                        <button>More <i className="fa-solid fa-chevron-down"></i></button>
                                    </div>
                                    <div className="header-right-top-content-myselft">
                                        <div className="header-right-top-content-myselft-information">
                                            <i className="fa-solid fa-bell"></i>
                                            <span className="thongbao-bell">8</span>
                                            <div className="right-top-content-myselft-information-table">
                                                <ul className="ul-tamgiac-informaintion">
                                                    <li>
                                                        <img src="http://localhost:3000/images/admin/anhthongtin.jpg" alt="" />
                                                        <div className="thongtin-bell-information">
                                                            <h4>Tin Cấp Báo</h4>
                                                            <span>
                                                                Ăn Ngủ và Code
                                                            </span>
                                                        </div>
                                                    </li>
                                                    <li>
                                                        <img src="http://localhost:3000/images/admin/anhthongtin.jpg" alt="" />
                                                        <div className="thongtin-bell-information">
                                                            <h4>Tin Cấp Báo</h4>
                                                            <span>
                                                                Ăn Ngủ và Code
                                                            </span>
                                                        </div>
                                                    </li>
                                                    <li>
                                                        <img src="http://localhost:3000/images/admin/anhthongtin.jpg" alt="" />
                                                        <div className="thongtin-bell-information">
                                                            <h4>Tin Cấp Báo</h4>
                                                            <span>
                                                                Ăn Ngủ và Code
                                                            </span>
                                                        </div>
                                                    </li>
                                                    <li>
                                                        <img src="http://localhost:3000/images/admin/anhthongtin.jpg" alt="" />
                                                        <div className="thongtin-bell-information">
                                                            <h4>Tin Cấp Báo</h4>
                                                            <span>
                                                                Ăn Ngủ và Code
                                                            </span>
                                                        </div>
                                                    </li>
                                                    <li>
                                                        <img src="http://localhost:3000/images/admin/anhthongtin.jpg" alt="" />
                                                        <div className="thongtin-bell-information">
                                                            <h4>Tin Cấp Báo</h4>
                                                            <span>
                                                                Ăn Ngủ và Code
                                                            </span>
                                                        </div>
                                                    </li>
                                                </ul>
                                            </div>
                                        </div>
                                        <div className="right-top-content-myselft-img">
                                            <img src="http://localhost:3000/images/admin/Raica.jpg" alt="" />
                                        </div>
                                        <div className="right-top-content-myselft-content">
                                            <span>Nguyễn Trung Nhịn <i className="fa-solid fa-caret-down"></i>
                                                <div className="top-content-myselft-content-table">
                                                    <ul className="ul-tamgiac">
                                                        <li>
                                                            <Link href="#"> <i className="fa-solid fa-user"></i> Thông Tin Cá Nhân</Link>
                                                        </li>
                                                        <li>
                                                            <Link href="#"><i className="fa-solid fa-gear"></i> Cài Đặt</Link>
                                                        </li>
                                                        <li>
                                                            <Link href="/">
                                                                <i className="fa-solid fa-right-from-bracket"></i>Thoát
                                                            </Link>
                                                        </li>
                                                    </ul>
                                                </div>
                                            </span>
                                        </div>
                                    </div>
                                </div>
                                {/* <div className="main-right-top-content"> */}
                                {children}
                                {/* </div> */}
                            </div>
                        </div>
                    </div>
                </div>
                <script src="https://kit.fontawesome.com/bcd15b30db.js" crossorigin="anonymous"></script>
                <script src="/bootstrap/js/bootstrap.bundle.min.js"></script>
            </body>
        </html>
    );
}