import { Inter } from "next/font/google";
import "../../../public/bootstrap/css/bootstrap.min.css";
import Header from "./header";
import Footer from "./footer";
import Providers from "../../../redux/Provider";



const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet' />
        <meta charset="UTF-8"></meta>
      </head>
      <body className={inter.className}>
        <Providers>
          <Header />
          {children}
          <Footer />
        </Providers>
        <script src="https://kit.fontawesome.com/2b5ed98ab2.js" crossOrigin="anonymous"></script>
        <script src="/bootstrap/js/bootstrap.bundle.min.js"></script>
      </body>
    </html>
  );
}
